name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: terraform-project

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-project

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform-project
